### ISSUE TITLE
[alfabank-by] Connecting as a non-resident doesn't work with error 42

### ISSUE THREAD

**Issue by podabed** [zenmoney/ZenPlugins#389] opened 2019-09-25 10:02 UTC
When I checked that I'm non resident plugin requires passport number as I'm a resident. After I typed my russian passport number, of course, bank send error.

![photo_2019-09-25 12 59 54](https://user-images.githubusercontent.com/4352168/65591057-799d0c00-df94-11e9-8a9c-1959829f9d10.jpeg)
![photo_2019-09-25 12 59 57](https://user-images.githubusercontent.com/4352168/65591058-799d0c00-df94-11e9-9ca7-84ae547ad0da.jpeg)

**Comment by vetheslav** [comment] 2019-09-25 18:54
@podabed There's a special field in the setting of the plugin "Резидент РБ". It means are you a resident or no. You should set it as false and try again. Then you should fill the same password number that you use to enter into Insync.by Mobile Application. It's not the same login and password that you use for WEB version.

**Comment by podabed** [comment] 2019-09-26 09:52
Sorry, maybe I explained too confuse. When I selected «Резидент РБ» as false or true I see the same dialog with «Введите номер белорусского паспорта (Формат: 3111111А111РВ1)».

**Comment by vetheslav** [comment] 2019-09-27 12:22
@podabed Interesting... I changed that logic a few versions ago. Could you remove current integration with the bank and start setting up again?

**Comment by podabed** [comment] 2019-09-27 13:18
This is the first integration and the only.

**Comment by vetheslav** [comment] 2019-09-28 19:35
@podabed Could you please share your log? You can find special button in the plugin's setting page.

**Comment by podabed** [comment] 2019-09-29 08:22
@vetheslav, I can't do this because these settings available only after successful connect.

**Comment by vetheslav** [comment] 2019-09-30 15:55
@podabed, unfortunately, I don't know how to help... I can't reproduce your case on my phone and on my local computer.
@skvav or @jonny3D , could you help here? I think there's something strange on the mobile application.
@podabed as an idea, have you downloaded the latest version of ZenMoney App?

**Comment by podabed** [comment] 2019-09-30 16:02
@vetheslav, of course, latest. Can I debug plugin on my device?

**Comment by vetheslav** [comment] 2019-09-30 18:37
@podabed I don't think so. Even I can debug it only on the laptop.

**Comment by podabed** [comment] 2019-09-30 19:22
Could you build special app version for me with enabled logging or something else?

**Comment by vetheslav** [comment] 2019-10-02 18:12
@podabed, unfortunately, I can't because I'm not a developer of ZenMooney. I'm just helping with some integrations with Belarussian banks. But @skvav or @jonny3D might help here

**Comment by podabed** [comment] 2019-10-03 06:04
@skvav, @jonny3D, could you please build special app version for me with enabled logging?

**Comment by skvav** [comment] 2019-10-08 09:34
Should be fixed in 6f48282. @podabed please try connect again and let us know if the problem remains.

**Comment by vetheslav** [comment] 2019-10-17 16:43
@podabed @skvav I think we could close that issue

**Closed** 2019-10-23 06:51 UTC
